// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: grpc/auth-service/auth-service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password      *string                `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_grpc_auth_service_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_service_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_service_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

var File_grpc_auth_service_auth_service_proto protoreflect.FileDescriptor

const file_grpc_auth_service_auth_service_proto_rawDesc = "" +
	"\n" +
	"$grpc/auth-service/auth-service.proto\x12\x13lovify_auth_service\x1a\x1bgoogle/protobuf/empty.proto\"I\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2[\n" +
	"\vAuthService\x12L\n" +
	"\fRegisterUser\x12$.lovify_auth_service.RegisterRequest\x1a\x16.google.protobuf.EmptyB\x15Z\x13lovify-auth/serviceb\beditionsp\xe8\a"

var (
	file_grpc_auth_service_auth_service_proto_rawDescOnce sync.Once
	file_grpc_auth_service_auth_service_proto_rawDescData []byte
)

func file_grpc_auth_service_auth_service_proto_rawDescGZIP() []byte {
	file_grpc_auth_service_auth_service_proto_rawDescOnce.Do(func() {
		file_grpc_auth_service_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auth_service_auth_service_proto_rawDesc), len(file_grpc_auth_service_auth_service_proto_rawDesc)))
	})
	return file_grpc_auth_service_auth_service_proto_rawDescData
}

var file_grpc_auth_service_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_auth_service_auth_service_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: lovify_auth_service.RegisterRequest
	(*emptypb.Empty)(nil),   // 1: google.protobuf.Empty
}
var file_grpc_auth_service_auth_service_proto_depIdxs = []int32{
	0, // 0: lovify_auth_service.AuthService.RegisterUser:input_type -> lovify_auth_service.RegisterRequest
	1, // 1: lovify_auth_service.AuthService.RegisterUser:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_auth_service_auth_service_proto_init() }
func file_grpc_auth_service_auth_service_proto_init() {
	if File_grpc_auth_service_auth_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auth_service_auth_service_proto_rawDesc), len(file_grpc_auth_service_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auth_service_auth_service_proto_goTypes,
		DependencyIndexes: file_grpc_auth_service_auth_service_proto_depIdxs,
		MessageInfos:      file_grpc_auth_service_auth_service_proto_msgTypes,
	}.Build()
	File_grpc_auth_service_auth_service_proto = out.File
	file_grpc_auth_service_auth_service_proto_goTypes = nil
	file_grpc_auth_service_auth_service_proto_depIdxs = nil
}
